services:
  engine:
    container_name: ai-voice-connector-engine
    build:
      context: ../../
      dockerfile: ./docker/Dockerfile
    network_mode: host
    volumes:
      - ./conn:/app/cfg/
    environment:
      CONFIG_FILE: /app/cfg/simple.ini
    env_file:
      - .env
    depends_on:
      opensips:
        condition: service_healthy

  opensips:
    container_name: ai-voice-connector-opensips
    build:
      dockerfile_inline: |
        FROM opensips/opensips:latest
        RUN apt -y update && apt -y install gettext-base
      args:
        OPENSIPS_CLI: true
    command: -p /etc/opensips/substenv.sh
    volumes:
      - ./b2b:/etc/opensips/
    network_mode: host
    env_file:
      - .env
    healthcheck:
      test: opensips-cli -x mi sr_get_status core | grep -q 'running'
      interval: 1s
      retries: 10
      timeout: 2s
