services:
  engine:
    container_name: ai-voice-connector-engine
    build:
      context: ../../
      dockerfile: ./docker/Dockerfile
      args:
        EXTRA_MODULES: "websocket-client dotenv"
    network_mode: host
    volumes:
      - ./conn:/app/cfg/
    environment:
      CONFIG_FILE: /app/cfg/demo.ini
    env_file:
      - .env

  opensips:
    container_name: ai-voice-connector-opensips
    build:
      dockerfile_inline: |
        FROM opensips/opensips:latest
        RUN apt -y update && apt -y install gettext-base
    volumes:
      - ./os:/etc/opensips/
    network_mode: host
    command: -p /etc/opensips/substenv.sh
    env_file:
      - .env

  b2b_opensips:
    container_name: ai-voice-connector-b2b_opensips
    build:
      dockerfile_inline: |
        FROM opensips/opensips:latest
        RUN apt -y update && apt -y install gettext-base
    volumes:
      - ./b2b:/etc/opensips/
    network_mode: host
    command: -p /etc/opensips/substenv.sh
    env_file:
      - .env

  freeswitch:
    container_name: ai-voice-connector-freeswitch
    image: opensips/freeswitch-ce
    cap_add:
      - SYS_NICE
    volumes:
      - ./fs/dialplan:/tmp/dialplan
      - ./fs/entrypoint.d:/docker-entrypoint.d
    network_mode: host
    env_file:
      - .env
